-- Phase 3 Migration: Side Events (Pre/Post Round) Schema
-- Adds side_events and side_event_registrations tables for managing rounds separate from main tournament registration

-- =========
-- 6) Side Events (Pre/Post Rounds)
-- =========
create table if not exists public.side_events (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  round_type text not null check (round_type in ('pre', 'post')),
  title text not null,
  tee_time text,
  location text,
  notes text,
  open_at timestamptz,
  close_at timestamptz,
  max_participants integer,
  status text not null default 'draft' check (status in ('draft','open','closed','done')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_side_events_updated_at on public.side_events;
create trigger trg_side_events_updated_at
before update on public.side_events
for each row
execute function public.set_updated_at();

-- =========
-- 7) Side Event Registrations
-- =========
create table if not exists public.side_event_registrations (
  id bigint generated by default as identity primary key,
  side_event_id bigint not null references public.side_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  status text not null default 'applied'
    check (status in ('applied','confirmed','waitlisted','canceled')),
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (side_event_id, user_id)
);

drop trigger if exists trg_side_event_registrations_updated_at on public.side_event_registrations;
create trigger trg_side_event_registrations_updated_at
before update on public.side_event_registrations
for each row
execute function public.set_updated_at();

-- =========
-- RLS: Side Events & Side Event Registrations
-- =========
alter table public.side_events enable row level security;
alter table public.side_event_registrations enable row level security;

-- ---- Side Events policies
-- Anyone can read side_events (public list)
drop policy if exists "side_events_select_public" on public.side_events;
create policy "side_events_select_public"
on public.side_events for select
using (true);

-- Admins can insert/update/delete side_events
drop policy if exists "side_events_write_admin" on public.side_events;
create policy "side_events_write_admin"
on public.side_events for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- ---- Side Event Registrations policies
-- Anyone can read side_event_registrations (public status view)
drop policy if exists "side_event_registrations_select_public" on public.side_event_registrations;
create policy "side_event_registrations_select_public"
on public.side_event_registrations for select
using (true);

-- Authenticated users can insert their own side event registration
drop policy if exists "side_event_registrations_insert_own" on public.side_event_registrations;
create policy "side_event_registrations_insert_own"
on public.side_event_registrations for insert
with check (auth.uid() = user_id);

-- Users can update/cancel their own side event registration
drop policy if exists "side_event_registrations_update_own" on public.side_event_registrations;
create policy "side_event_registrations_update_own"
on public.side_event_registrations for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Admin can update anyone (for confirm/waitlist etc.)
drop policy if exists "side_event_registrations_admin_update" on public.side_event_registrations;
create policy "side_event_registrations_admin_update"
on public.side_event_registrations for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- Trigger to log side event registration changes
create or replace function public.log_side_event_registration_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'INSERT') then
    insert into public.audit_logs(entity_type, entity_id, action, actor_id, before, after)
    values ('side_event_registration', new.id, 'insert', auth.uid(), null, to_jsonb(new));
    return new;
  elsif (tg_op = 'UPDATE') then
    insert into public.audit_logs(entity_type, entity_id, action, actor_id, before, after)
    values ('side_event_registration', new.id, 'update', auth.uid(), to_jsonb(old), to_jsonb(new));
    return new;
  elsif (tg_op = 'DELETE') then
    insert into public.audit_logs(entity_type, entity_id, action, actor_id, before, after)
    values ('side_event_registration', old.id, 'delete', auth.uid(), to_jsonb(old), null);
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_log_side_event_registration_changes on public.side_event_registrations;
create trigger trg_log_side_event_registration_changes
after insert or update or delete on public.side_event_registrations
for each row
execute function public.log_side_event_registration_changes();
