-- Migration: 005_meal_options.sql
-- Purpose: 식사 메뉴 옵션 시스템 구축 (관리자가 옵션 생성, 참가자가 선택)
-- Date: 2026-02-09
-- 
-- 이 마이그레이션은 Supabase SQL Editor에서 수동으로 실행해야 합니다.

-- =========================================
-- 1) tournament_meal_options 테이블 생성
-- =========================================
create table if not exists public.tournament_meal_options (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  menu_name text not null,
  is_active boolean not null default true,
  display_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 인덱스 생성 (성능 최적화)
create index if not exists idx_tournament_meal_options_tournament_id
on public.tournament_meal_options(tournament_id);

create index if not exists idx_tournament_meal_options_active
on public.tournament_meal_options(tournament_id, is_active, display_order);

-- updated_at 자동 갱신 트리거
drop trigger if exists trg_tournament_meal_options_updated_at on public.tournament_meal_options;
create trigger trg_tournament_meal_options_updated_at
before update on public.tournament_meal_options
for each row
execute function public.set_updated_at();

-- =========================================
-- 2) tournament_meal_options RLS 정책
-- =========================================
-- Enable RLS
alter table public.tournament_meal_options enable row level security;

-- SELECT: 로그인한 사용자 전체 조회 가능
create policy "Authenticated users can view meal options"
on public.tournament_meal_options
for select
using (auth.role() = 'authenticated');

-- INSERT: 관리자만
create policy "Admins can insert meal options"
on public.tournament_meal_options
for insert
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.is_admin = true
  )
);

-- UPDATE: 관리자만
create policy "Admins can update meal options"
on public.tournament_meal_options
for update
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.is_admin = true
  )
);

-- DELETE: 관리자만 (soft delete 권장이므로 실제로는 사용 안 할 수 있음)
create policy "Admins can delete meal options"
on public.tournament_meal_options
for delete
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.is_admin = true
  )
);

-- =========================================
-- 3) registrations 테이블에 meal_option_id 컬럼 추가
-- =========================================
-- meal_option_id 추가 (nullable, 참가자가 선택 안 할 수도 있음)
alter table public.registrations
add column if not exists meal_option_id bigint references public.tournament_meal_options(id) on delete set null;

-- 인덱스 추가 (조인 성능 향상)
create index if not exists idx_registrations_meal_option_id
on public.registrations(meal_option_id);

-- =========================================
-- 4) 기존 데이터 호환성 확인
-- =========================================
-- 기존 registrations 레코드는 meal_option_id가 null로 설정됨
-- 추후 참가자가 수정하거나 관리자가 직접 설정 가능

-- =========================================
-- 5) 샘플 데이터 (선택 사항, 테스트용)
-- =========================================
-- 예시: tournament_id=1에 대한 기본 식사 메뉴 옵션
-- insert into public.tournament_meal_options (tournament_id, menu_name, display_order)
-- values 
--   (1, '한식 (불고기)', 1),
--   (1, '양식 (스테이크)', 2),
--   (1, '중식 (짜장면)', 3),
--   (1, '선택 안 함', 4);

-- =========================================
-- 완료 메시지
-- =========================================
-- 이 마이그레이션 실행 후:
-- 1. 관리자는 대회별로 식사 메뉴 옵션을 생성/관리할 수 있음
-- 2. 참가자는 신청 시 등록된 메뉴 중에서 선택
-- 3. 메뉴 옵션은 is_active=false로 비활성화 가능 (soft delete)
-- 4. display_order로 표시 순서 제어
--
-- 다음 단계: 
-- - /admin/tournaments/[id]/meal-options 페이지 구현
-- - /t/[id] 신청 폼에 메뉴 선택 UI 추가
