-- Migration: 006_registration_extras.sql
-- Purpose: Registration extras (carpool/transport/departure/notes)
-- Date: 2026-02-09
--
-- Run this script manually in Supabase SQL Editor.

-- =========================================
-- 1) Create registration_extras table
-- =========================================
create table if not exists public.registration_extras (
  id bigint generated by default as identity primary key,
  registration_id bigint not null unique references public.registrations(id) on delete cascade,
  carpool_available boolean not null default false,
  carpool_seats int,
  transportation text,
  departure_location text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_registration_extras_registration_id
on public.registration_extras(registration_id);

-- updated_at trigger
drop trigger if exists trg_registration_extras_updated_at on public.registration_extras;
create trigger trg_registration_extras_updated_at
before update on public.registration_extras
for each row
execute function public.set_updated_at();

-- =========================================
-- 2) registration_extras RLS policies
-- =========================================
alter table public.registration_extras enable row level security;

-- SELECT: owner or admin
create policy "Owners or admins can view registration extras"
on public.registration_extras
for select
using (
  exists (
    select 1 from public.registrations r
    where r.id = registration_extras.registration_id
      and r.user_id = auth.uid()
  )
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

-- INSERT: owner only
create policy "Owners can insert registration extras"
on public.registration_extras
for insert
with check (
  exists (
    select 1 from public.registrations r
    where r.id = registration_extras.registration_id
      and r.user_id = auth.uid()
  )
);

-- UPDATE: owner or admin
create policy "Owners or admins can update registration extras"
on public.registration_extras
for update
using (
  exists (
    select 1 from public.registrations r
    where r.id = registration_extras.registration_id
      and r.user_id = auth.uid()
  )
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

-- DELETE: owner or admin
create policy "Owners or admins can delete registration extras"
on public.registration_extras
for delete
using (
  exists (
    select 1 from public.registrations r
    where r.id = registration_extras.registration_id
      and r.user_id = auth.uid()
  )
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

-- =========================================
-- 3) Public carpool function (limited fields)
-- =========================================
-- Exposes: nickname, carpool_available, carpool_seats
create or replace function public.get_carpool_public(p_tournament_id bigint)
returns table (
  registration_id bigint,
  nickname text,
  carpool_available boolean,
  carpool_seats int
)
language sql
security definer
set search_path = public
as $$
  select
    r.id as registration_id,
    r.nickname,
    e.carpool_available,
    e.carpool_seats
  from public.registrations r
  join public.registration_extras e on e.registration_id = r.id
  where r.tournament_id = p_tournament_id
    and r.status <> 'canceled'
    and e.carpool_available = true;
$$;

revoke all on function public.get_carpool_public(bigint) from public;
grant execute on function public.get_carpool_public(bigint) to authenticated;

-- =========================================
-- Notes
-- =========================================
-- 1) Users can save/update their own extras
-- 2) Admins can read all extras
-- 3) Authenticated users can see limited carpool data via the function
