-- Migration: 007_tournament_groups.sql
-- Purpose: Tournament groups and members (web-based grouping + publish)
-- Date: 2026-02-09
--
-- Run this script manually in Supabase SQL Editor.

-- =========================================
-- 1) tournament_groups table
-- =========================================
create table if not exists public.tournament_groups (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  group_no int not null,
  tee_time text,
  is_published boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, group_no)
);

create index if not exists idx_tournament_groups_tournament_id
on public.tournament_groups(tournament_id);

create index if not exists idx_tournament_groups_published
on public.tournament_groups(tournament_id, is_published);

-- updated_at trigger
drop trigger if exists trg_tournament_groups_updated_at on public.tournament_groups;
create trigger trg_tournament_groups_updated_at
before update on public.tournament_groups
for each row
execute function public.set_updated_at();

-- =========================================
-- 2) tournament_group_members table
-- =========================================
create table if not exists public.tournament_group_members (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.tournament_groups(id) on delete cascade,
  registration_id bigint not null references public.registrations(id) on delete cascade,
  position int not null check (position between 1 and 4),
  role text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (group_id, position),
  unique (registration_id)
);

create index if not exists idx_tournament_group_members_group_id
on public.tournament_group_members(group_id);

create index if not exists idx_tournament_group_members_registration_id
on public.tournament_group_members(registration_id);

-- updated_at trigger
drop trigger if exists trg_tournament_group_members_updated_at on public.tournament_group_members;
create trigger trg_tournament_group_members_updated_at
before update on public.tournament_group_members
for each row
execute function public.set_updated_at();

-- =========================================
-- 3) RLS policies
-- =========================================
alter table public.tournament_groups enable row level security;
alter table public.tournament_group_members enable row level security;

-- tournament_groups SELECT: authenticated + (published or admin)
create policy "Authenticated users can view published groups"
on public.tournament_groups
for select
using (
  auth.role() = 'authenticated'
  and (
    is_published = true
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
);

-- tournament_groups write: admin only
create policy "Admins can insert groups"
on public.tournament_groups
for insert
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

create policy "Admins can update groups"
on public.tournament_groups
for update
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

create policy "Admins can delete groups"
on public.tournament_groups
for delete
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

-- tournament_group_members SELECT: authenticated + (group published or admin)
create policy "Authenticated users can view published group members"
on public.tournament_group_members
for select
using (
  auth.role() = 'authenticated'
  and (
    exists (
      select 1 from public.tournament_groups g
      where g.id = tournament_group_members.group_id
        and g.is_published = true
    )
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.is_admin = true
    )
  )
);

-- tournament_group_members write: admin only
create policy "Admins can insert group members"
on public.tournament_group_members
for insert
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

create policy "Admins can update group members"
on public.tournament_group_members
for update
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

create policy "Admins can delete group members"
on public.tournament_group_members
for delete
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true
  )
);

-- =========================================
-- Notes
-- =========================================
-- 1) Published groups are visible to authenticated users
-- 2) Admins can view and edit all groups/members
-- 3) registration_id is unique (one player per group)
