-- Migration: 030_live_group_draw_sessions_and_events.sql
-- Purpose: Live group draw sessions/events schema with base RLS policies
-- Date: 2026-02-13

-- =========================================
-- 1) draw_sessions
-- =========================================
create table if not exists public.draw_sessions (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'live', 'finished', 'canceled')),
  group_count int not null check (group_count > 0),
  group_size int not null check (group_size > 0),
  total_players int not null check (total_players >= 0),
  player_ids bigint[] not null default '{}'::bigint[],
  current_step int not null default 0 check (current_step >= 0),
  started_at timestamptz,
  ended_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_draw_sessions_tournament_id
on public.draw_sessions(tournament_id);

create index if not exists idx_draw_sessions_status
on public.draw_sessions(status);

drop trigger if exists trg_draw_sessions_updated_at on public.draw_sessions;
create trigger trg_draw_sessions_updated_at
before update on public.draw_sessions
for each row
execute function public.set_updated_at();

-- =========================================
-- 2) draw_events (append-only event log)
-- =========================================
create table if not exists public.draw_events (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.draw_sessions(id) on delete cascade,
  step int not null check (step >= 0),
  event_type text not null
    check (event_type in (
      'SESSION_STARTED',
      'STEP_CONFIGURED',
      'PICK_RESULT',
      'ASSIGN_UPDATED',
      'ASSIGN_CONFIRMED',
      'MEMBER_MOVED',
      'UNDO_LAST'
    )),
  payload jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_draw_events_session_id
on public.draw_events(session_id);

create index if not exists idx_draw_events_session_step
on public.draw_events(session_id, step);

create index if not exists idx_draw_events_session_created_at
on public.draw_events(session_id, created_at);

-- =========================================
-- 3) RLS policies
-- =========================================
alter table public.draw_sessions enable row level security;
alter table public.draw_events enable row level security;

-- draw_sessions: authenticated users can read
drop policy if exists "Authenticated users can view draw sessions" on public.draw_sessions;
create policy "Authenticated users can view draw sessions"
on public.draw_sessions
for select
using (auth.role() = 'authenticated');

-- draw_sessions: admin write only
drop policy if exists "Admins can insert draw sessions" on public.draw_sessions;
create policy "Admins can insert draw sessions"
on public.draw_sessions
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can update draw sessions" on public.draw_sessions;
create policy "Admins can update draw sessions"
on public.draw_sessions
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- draw_events: authenticated users can read
drop policy if exists "Authenticated users can view draw events" on public.draw_events;
create policy "Authenticated users can view draw events"
on public.draw_events
for select
using (auth.role() = 'authenticated');

-- draw_events: admin insert only (append-only log)
drop policy if exists "Admins can insert draw events" on public.draw_events;
create policy "Admins can insert draw events"
on public.draw_events
for insert
with check (public.is_admin(auth.uid()));
