-- Migration: 035_live_draw_chat_sessions_and_messages.sql
-- Purpose: Add live draw chat session/message schema with RLS and Realtime publication
-- Date: 2026-03-07
-- Run this script manually in Supabase SQL Editor.

-- =========================================
-- 1) draw_chat_sessions
-- =========================================
create table if not exists public.draw_chat_sessions (
  id bigint generated by default as identity primary key,
  draw_session_id bigint not null references public.draw_sessions(id) on delete cascade,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  status text not null default 'live'
    check (status in ('live', 'closed')),
  started_by uuid references auth.users(id),
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint draw_chat_sessions_draw_session_unique unique (draw_session_id)
);

create index if not exists idx_draw_chat_sessions_tournament_id
on public.draw_chat_sessions(tournament_id);

create index if not exists idx_draw_chat_sessions_status
on public.draw_chat_sessions(status);

drop trigger if exists trg_draw_chat_sessions_updated_at on public.draw_chat_sessions;
create trigger trg_draw_chat_sessions_updated_at
before update on public.draw_chat_sessions
for each row
execute function public.set_updated_at();

-- =========================================
-- 2) draw_chat_messages (append-only)
-- =========================================
create table if not exists public.draw_chat_messages (
  id bigint generated by default as identity primary key,
  chat_session_id bigint not null references public.draw_chat_sessions(id) on delete cascade,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  nickname text not null,
  message text not null,
  created_at timestamptz not null default now(),
  constraint draw_chat_messages_nickname_not_blank
    check (char_length(btrim(nickname)) between 1 and 40),
  constraint draw_chat_messages_message_not_blank
    check (char_length(btrim(message)) between 1 and 300)
);

create index if not exists idx_draw_chat_messages_chat_session_id
on public.draw_chat_messages(chat_session_id);

create index if not exists idx_draw_chat_messages_chat_session_created_at
on public.draw_chat_messages(chat_session_id, created_at);

create index if not exists idx_draw_chat_messages_tournament_id
on public.draw_chat_messages(tournament_id);

-- =========================================
-- 3) RLS policies
-- =========================================
alter table public.draw_chat_sessions enable row level security;
alter table public.draw_chat_messages enable row level security;

-- draw_chat_sessions: authenticated users can read
-- (권한 범위 세분화는 추후 정책 결정 후 강화)
drop policy if exists "Authenticated users can view draw chat sessions" on public.draw_chat_sessions;
create policy "Authenticated users can view draw chat sessions"
on public.draw_chat_sessions
for select
using (auth.role() = 'authenticated');

-- draw_chat_sessions: admin write only
drop policy if exists "Admins can insert draw chat sessions" on public.draw_chat_sessions;
create policy "Admins can insert draw chat sessions"
on public.draw_chat_sessions
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can update draw chat sessions" on public.draw_chat_sessions;
create policy "Admins can update draw chat sessions"
on public.draw_chat_sessions
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- draw_chat_messages: authenticated users can read
-- (권한 범위 세분화는 추후 정책 결정 후 강화)
drop policy if exists "Authenticated users can view draw chat messages" on public.draw_chat_messages;
create policy "Authenticated users can view draw chat messages"
on public.draw_chat_messages
for select
using (auth.role() = 'authenticated');

-- draw_chat_messages: authenticated users can write own message when session is live
drop policy if exists "Users can insert own draw chat messages" on public.draw_chat_messages;
create policy "Users can insert own draw chat messages"
on public.draw_chat_messages
for insert
with check (
  auth.role() = 'authenticated'
  and user_id = auth.uid()
  and exists (
    select 1
    from public.draw_chat_sessions dcs
    where dcs.id = draw_chat_messages.chat_session_id
      and dcs.tournament_id = draw_chat_messages.tournament_id
      and dcs.status = 'live'
  )
);

-- draw_chat_messages: append-only (no update/delete for authenticated)

-- =========================================
-- 4) Realtime publication
-- =========================================
do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'draw_chat_sessions'
    ) then
      alter publication supabase_realtime add table public.draw_chat_sessions;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'draw_chat_messages'
    ) then
      alter publication supabase_realtime add table public.draw_chat_messages;
    end if;
  end if;
end
$$;
