-- Migration: 049_tournament_gallery.sql
-- Purpose: 대회 갤러리 (사진/영상 공유) 기능
--   - tournament_gallery_items : 이미지(Cloudinary) + 영상 링크(YouTube/Vimeo)
--   - tournament_gallery_likes : 좋아요
--   - tournament_gallery_comments : 댓글
-- Date: 2026-03-30
--
-- 본 SQL은 Supabase SQL Editor에서 수동 실행합니다.

-- ============================================================================
-- 1) 갤러리 아이템
-- ============================================================================

create table if not exists public.tournament_gallery_items (
  id              bigint generated by default as identity primary key,
  tournament_id   bigint not null references public.tournaments(id) on delete cascade,
  user_id         uuid   not null references auth.users(id) on delete cascade,

  -- 미디어 타입: image | video_link
  media_type      text   not null check (media_type in ('image', 'video_link')),

  -- 이미지 (Cloudinary)
  cloudinary_public_id  text,         -- e.g. "just-golf/gallery/68/uuid"
  public_url            text,         -- Cloudinary secure_url

  -- 영상 링크 (YouTube / Vimeo)
  video_url             text,
  thumbnail_url         text,         -- oEmbed에서 추출한 썸네일
  video_title           text,         -- oEmbed에서 추출한 제목

  -- 공통
  caption         text   check (char_length(caption) <= 300),
  is_hidden       boolean not null default false,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- 이미지 or 영상 링크 중 하나는 반드시 있어야 함
  constraint chk_gallery_media_content check (
    (media_type = 'image'      and cloudinary_public_id is not null and public_url is not null)
    or
    (media_type = 'video_link' and video_url is not null)
  )
);

create index if not exists idx_gallery_items_tournament_created
  on public.tournament_gallery_items(tournament_id, created_at desc);

create index if not exists idx_gallery_items_user
  on public.tournament_gallery_items(user_id);

drop trigger if exists trg_gallery_items_updated_at on public.tournament_gallery_items;
create trigger trg_gallery_items_updated_at
  before update on public.tournament_gallery_items
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 2) 좋아요
-- ============================================================================

create table if not exists public.tournament_gallery_likes (
  id         bigint generated by default as identity primary key,
  item_id    bigint not null references public.tournament_gallery_items(id) on delete cascade,
  user_id    uuid   not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),

  unique (item_id, user_id)   -- 동일 사용자 중복 좋아요 불가
);

create index if not exists idx_gallery_likes_item
  on public.tournament_gallery_likes(item_id);

-- ============================================================================
-- 3) 댓글
-- ============================================================================

create table if not exists public.tournament_gallery_comments (
  id         bigint generated by default as identity primary key,
  item_id    bigint not null references public.tournament_gallery_items(id) on delete cascade,
  user_id    uuid   not null references auth.users(id) on delete cascade,
  content    text   not null check (char_length(content) between 1 and 500),
  is_hidden  boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_gallery_comments_item_created
  on public.tournament_gallery_comments(item_id, created_at);

drop trigger if exists trg_gallery_comments_updated_at on public.tournament_gallery_comments;
create trigger trg_gallery_comments_updated_at
  before update on public.tournament_gallery_comments
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 4) RLS 활성화
-- ============================================================================

alter table public.tournament_gallery_items    enable row level security;
alter table public.tournament_gallery_likes    enable row level security;
alter table public.tournament_gallery_comments enable row level security;

-- ============================================================================
-- 5) RLS 정책 — tournament_gallery_items
-- ============================================================================

-- 조회: 로그인 사용자 (is_hidden=false 또는 관리자)
drop policy if exists "갤러리 아이템 조회" on public.tournament_gallery_items;
create policy "갤러리 아이템 조회"
  on public.tournament_gallery_items for select
  using (
    auth.role() = 'authenticated'
    and (
      is_hidden = false
      or public.is_admin_secure(auth.uid())
    )
  );

-- 등록: 승인된 로그인 사용자 (본인 user_id 일치 필수)
drop policy if exists "갤러리 아이템 등록" on public.tournament_gallery_items;
create policy "갤러리 아이템 등록"
  on public.tournament_gallery_items for insert
  with check (
    auth.role() = 'authenticated'
    and auth.uid() = user_id
    and public.is_approved_user(auth.uid())
  );

-- 수정: 본인(caption) 또는 관리자(is_hidden 포함)
drop policy if exists "갤러리 아이템 수정" on public.tournament_gallery_items;
create policy "갤러리 아이템 수정"
  on public.tournament_gallery_items for update
  using (
    auth.uid() = user_id
    or public.is_admin_secure(auth.uid())
  )
  with check (
    auth.uid() = user_id
    or public.is_admin_secure(auth.uid())
  );

-- 삭제: 본인 또는 관리자
drop policy if exists "갤러리 아이템 삭제" on public.tournament_gallery_items;
create policy "갤러리 아이템 삭제"
  on public.tournament_gallery_items for delete
  using (
    auth.uid() = user_id
    or public.is_admin_secure(auth.uid())
  );

-- ============================================================================
-- 6) RLS 정책 — tournament_gallery_likes
-- ============================================================================

drop policy if exists "갤러리 좋아요 조회" on public.tournament_gallery_likes;
create policy "갤러리 좋아요 조회"
  on public.tournament_gallery_likes for select
  using (auth.role() = 'authenticated');

drop policy if exists "갤러리 좋아요 등록" on public.tournament_gallery_likes;
create policy "갤러리 좋아요 등록"
  on public.tournament_gallery_likes for insert
  with check (
    auth.role() = 'authenticated'
    and auth.uid() = user_id
  );

drop policy if exists "갤러리 좋아요 삭제" on public.tournament_gallery_likes;
create policy "갤러리 좋아요 삭제"
  on public.tournament_gallery_likes for delete
  using (auth.uid() = user_id);

-- ============================================================================
-- 7) RLS 정책 — tournament_gallery_comments
-- ============================================================================

drop policy if exists "갤러리 댓글 조회" on public.tournament_gallery_comments;
create policy "갤러리 댓글 조회"
  on public.tournament_gallery_comments for select
  using (
    auth.role() = 'authenticated'
    and (
      is_hidden = false
      or public.is_admin_secure(auth.uid())
    )
  );

drop policy if exists "갤러리 댓글 등록" on public.tournament_gallery_comments;
create policy "갤러리 댓글 등록"
  on public.tournament_gallery_comments for insert
  with check (
    auth.role() = 'authenticated'
    and auth.uid() = user_id
    and public.is_approved_user(auth.uid())
  );

drop policy if exists "갤러리 댓글 삭제" on public.tournament_gallery_comments;
create policy "갤러리 댓글 삭제"
  on public.tournament_gallery_comments for delete
  using (
    auth.uid() = user_id
    or public.is_admin_secure(auth.uid())
  );

-- ============================================================================
-- 완료 로그
-- ============================================================================

do $$
begin
  raise notice '================================================';
  raise notice 'Migration 049_tournament_gallery.sql 완료';
  raise notice '================================================';
  raise notice '생성된 테이블:';
  raise notice '  - tournament_gallery_items';
  raise notice '  - tournament_gallery_likes';
  raise notice '  - tournament_gallery_comments';
  raise notice '';
  raise notice '다음 단계:';
  raise notice '  - Cloudinary 환경변수 추가 (.env.local, .env.production.local)';
  raise notice '    CLOUDINARY_CLOUD_NAME=';
  raise notice '    CLOUDINARY_API_KEY=';
  raise notice '    CLOUDINARY_API_SECRET=';
  raise notice '================================================';
end
$$;
